Dockerfile, README.md, poetry.lock, pyproject.toml
Neighbors asked us to refine the version number for our solution. (in README we have 3.12.*, but we used 3.12.4 in Dockerfile and Poetry pyproject.toml). Neighbors wants to avoid to change the version in the Docker image on test-infra every time when we need to change version in our solution. So, they asked us to refine our configuration. 
- Change `3.12.4` to `~3.12` in pyproject.toml
- Change `python:3.12.4-slim-bullseye` to `python:3.12-slim-bullseye` in Dockerfile
=> chore: refine version number for image builder

tests/blackbox/data/validation/kyma_app_apirule_broken.yml, tests/blackbox/data/validation/kyma_app_serverless_syntax_err.yml, tests/blackbox/data/validation/nginx_oom.yml, tests/blackbox/data/validation/nginx_wrong_image.yml, tests/blackbox/src/validation/utils/data_loader.py
- one validation file can now contain more than one mock response.
- added another mock response
=> feat: load validations as list from file

tests/blackbox/data/evaluation/namespace-scoped/kyma_app_apirule_broken/deployment.yml, tests/blackbox/data/evaluation/namespace-scoped/kyma_app_apirule_broken/scenario.yml, tests/blackbox/data/evaluation/namespace-scoped/kyma_app_serverless_syntax_err/deploy.sh, tests/blackbox/data/evaluation/namespace-scoped/kyma_app_serverless_syntax_err/deployment.yml, tests/blackbox/data/evaluation/namespace-scoped/kyma_app_serverless_syntax_err/scenario.yml, tests/blackbox/data/evaluation/namespace-scoped/nginx_oom/deployment.yml, tests/blackbox/data/evaluation/namespace-scoped/nginx_oom/scenario.yml, tests/blackbox/data/evaluation/namespace-scoped/nginx_wrong_image/deployment.yml, tests/blackbox/data/evaluation/namespace-scoped/nginx_wrong_image/scenario.yml, tests/blackbox/data/validation/kyma_app_apirule_broken.yml, tests/blackbox/data/validation/kyma_app_serverless_syntax_err.yml, tests/blackbox/data/validation/nginx_oom.yml, tests/blackbox/data/validation/nginx_wrong_image.yml
Fix blackbox deployment manifests:
- Fixes the deployment manifests naming.
**Example run(s)**
- https://github.com/kyma-project/kyma-companion/actions/runs/10737401383
> Note: the run failed because the required Kyma modules were not deployed, this will come in a follow-up PR.
=> chore: fix blackbox deployment manifests

.github/workflows/setup-test-cluster.yaml, scripts/shell/clean_up_cluster.sh, scripts/shell/deploy_kyma_modules.sh
Fix setup-gardener-test-cluster to deploy/cleanup Kyma modules:
- Deploy needed Kyma modules by the blackbox tests.
- Cleanup the deployed Kyma modules in the previous step.
**Example runs**
- https://github.com/kyma-project/kyma-companion/actions/runs/10769007826
=> chore: fix setup-gardener-test-cluster to deploy/cleanup Kyma modules

poetry.lock, src/agents/memory/redis_checkpointer.py, src/services/conversation.py, tests/services/test_conversation.py
Fix planner as it is broken due to usage of gpt-4o-mini.
- Use gpt-4o-mini for initial questions only
- Use gpt-4o for planner and ohter nodes of LangGraph
=> fix: use gpt-4o model for planner

.github/workflows/pull-evaluation-tests.yaml
- notify the contributor via a gh comment in the pr if the eval test was skipped (due to the missing label 'evaluation requested')
=> feat: add comment on gh pr if evaluation was skipped

tests/blackbox/src/common/config.py
The evaluation tests continuously fail because of rate limiting error.
- change worker to 1 to reduce parallelism
#196
=> fix: change workers to 1

tests/blackbox/src/common/config.py
- for setting up the gpt4.o mini model use the right env var
=> fix: reference to env var

src/agents/graph.py, src/utils/settings.py
There was no final response returned as the llm call of the Finalizer was broken. The `self.models` is a dictionary. A specific model needs to be chosen to access `llm`.
- use the `gpt4.o-mini` model in the Finalizer
=> fix: finalizer model call

doc_indexer/src/indexing/indexer.py, doc_indexer/src/main.py, doc_indexer/src/utils/hana.py, doc_indexer/src/utils/logging.py, doc_indexer/src/utils/models.py, doc_indexer/src/utils/settings.py, doc_indexer/tests/integration/indexing/test_indexer.py, doc_indexer/tests/unit/indexing/test_indexer.py, doc_indexer/tests/unit/utils/test_models.py
* Index with batches to prevent rate limiting
* Clean-up table after test run
* Add more logs
#199
=> chore: improve the Indexer

src/utils/config.py
Make temperature optional as some other models like embedding don't need temperature
- Make temperatur in model config optional
#200
=> fix: make temperature for models optional

src/agents/memory/redis_checkpointer.py, src/agents/supervisor/agent.py
- replace the [deprecated](https://docs.python.org/3/library/typing.html#typing.Sequence) `typing.Sequence` with `collections.abc.Sequence` 
- replace the [deprecated](https://docs.python.org/3/library/typing.html#typing.Tuple) `typing.Tuple` with the build in standard type [`tuple`](https://docs.python.org/3/library/stdtypes.html#tuple)
- remove unused imports and remove the corresponding `#noqa` instructions
=> refactor: clean up imports

src/rag/reranker/prompt.py, src/rag/reranker/reranker.py, tests/unit/rag/reranker/test_reranker.py
Use structured output in Kyma RAG reranker.
=> chore: use structured output in Kyma RAG reranker

.github/workflows/pull-integration-test.yaml
PR #274 moved env vars to a single JSON file. To ensure integration test runs with both formats, the YAML file was kept during the move to JSON: #303 
This legacy configuration can now be removed.
**Changes proposed in this pull request:**
- remove usage of `config.yml` in integration test
#197
=> test: remove legacy config.yml

Dockerfile
In the penultimate version of `Poetry` the option `--no-dev` for the `install` command was marked as deprecated. It looks like the last version now removed this option. Since we still used it in our `dockerfile` the job `Pull Build Image` ran into errors. This PR removes this option.
The option used to skip the dev dependencies like formatters.
=> fix: remove `--no-dev` instruction from `poetry install` in dockerfile

.github/workflows/pull-integration-test.yaml
Use separate GHA secret config json for integration tests. MODELS_JSON is used in other cases too. We need this test for rate limiting integration test.
#256
=> chore: use separate GHA secret for int tests

src/utils/settings.py
…s URL
- add user, password and database-number as configurables to build redis URL
=> feat: add user, password and database-number as configurables to build redis URL

.github/workflows/create-release.yml, .github/workflows/pull-integration-test.yaml, scripts/shell/check_publish_release_prerequisites.sh, scripts/shell/create_scan_config.sh, scripts/shell/create_sec_scanner_bump_pr.sh
- added integration tests
- Bumping image in sec-scanners-config on release branch as well.
=> chore: updated release pipeline

src/services/data_sanitizer.py, tests/unit/services/test_data_sanitizer.py
Enhance data sanitizer to remove last-applied-configuration
- Implemented _remove_last_applied_configuration method to delete the kubectl.kubernetes.io/last-applied-configuration annotation from Kubernetes resource objects.
- Added unit tests to verify the removal of the last-applied-configuration annotation from Deployment resources.
=> chore: enhance data sanitizer to remove last-applied-configuration

src/main.py
- add start options in `main.py` to allow debugg via [`debugpy`](https://pypi.org/project/debugpy/), the DAP implementation for Python that is supportet by NVim, as mentioned in the [official docs of FastAPI](https://fastapi.tiangolo.com/tutorial/debugging/)
=> feat: start options to support debugpy

docs/langfuse.md
- add docs how to deploy langfuse locally and on a k8s cluster for dev work.
#49
=> docs: deploy langfuse for development

src/routers/common.py
- made resource_name as optional parameter for initial questions. Because for cluster overview page, the name would be empty.
=> fix: made resource_name as optional parameter for initial questions

.github/workflows/lint-code.yml, .github/workflows/lint-pr-title.yml, .github/workflows/unit-test.yaml
- limit the `permissions` of the lint and unit-test workflows
=> chore: limit permissions of lint and unit

tests/unit/rag/reranker/test_reranker.py
At the moment, when we run the unit tests, we get the warning:
```
tests/unit/rag/reranker/test_reranker.py::TestLLMReranker::test_init
tests/unit/rag/reranker/test_reranker.py:35: PytestWarning: The test <Function test_init> is marked with '@pytest.mark.asyncio' but it is not an async function. Please remove the asyncio mark. If the test is not marked explicitly, check for global marks applied via 'pytestmark'.
def test_init(self):
```
so this PR will remove the decorators.
=> refactor: remove unuse decorator

src/agents/common/state.py, src/agents/k8s/tools/logs.py, src/agents/k8s/tools/query.py, src/agents/kyma/tools/query.py
At the moment we get the warning:
```
Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
```
when we run our tests and/or application.
The [migration guides](https://docs.pydantic.dev/latest/migration/#changes-to-config) for pydantic state that:
a) config classes
```
class MyClass(BaseModel):
class Config:
...
```
are deprecated and supposed to be replaced with `model_config = ConfigDict(...)`
b) `fields` configs are supposed to be replaced with `Annotate[... Field(...)]` 
And that is what this PR does.
In addition the …
=> refactor: remove config classes

pyproject.toml
we currently receive the warning
```
PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"
```
whenever we run tests for the application.
To prevent this, this PR set the ` asyncio_default_fixture_loop_scope` to `function`.
=> fix: set asyncio_default_fixture_loop_scope to function

.github/workflows/pull-evaluation-tests.yaml, src/routers/conversations.py
- use [`kubectl rollout check`](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_status/) to wait for the deployment
- check the readiness through the `NotePort` with a timeout and interval. 
=> refactor: enhance readyness-checks

src/agents/kyma/prompts.py, src/services/data_sanitizer.py, tests/integration/agents/kyma/test_kyma_agent_goal_accuracy.py, tests/unit/services/test_data_sanitizer.py
Kyma agent cannot handle too broad quries like "check all Kyma resources" not so well. We need to restrict it to certain resources for the time being. 
Delete managed fields field in metadata of k8s and kyma resources as it is not need to analyse resource.
- Updated Kyma agent prompts to require clarification for broad queries about Kyma resources, improving user interaction.
- Added new test cases to validate the agent's response when more information is needed from the user.
- Implemented a method in DataSanitizer to remove managedFields from metadata, ensuring cleaner resource definitions.
- Enhanced unit tests for DataSanitizer to cover the removal of managedFields in various scenarios.
=> feat: enhance Kyma agent prompts for too broad queries and delete managed fields from resources

src/agents/common/constants.py, src/agents/common/state.py, src/agents/graph.py, src/agents/prompts.py, src/utils/models/contants.py, src/utils/response.py, tests/integration/agents/test_gatekeeper_feedback.py, tests/integration/conftest.py, tests/unit/agents/test_graph.py, tests/unit/utils/test_response.py
Return feedback flag to the UI so that they can display feedback UI part for the end users
- Implement the logic in a separate LLM call and return the is_feedback flag as a part of Gatekeeper response
- Add/Update the int and unit tests
#491
=> feat: handle feedback

renovate.json
- group PRs by package, not for multiple package file (don't mix `test` dependencies from the main package and from the `indexer` package)
=> fix: group dep bumps by name but not by package file
